apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: tg-stats
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /tg_stats(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 80


