apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tg-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/nrf24l01/tg_group_statistics/backend:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "16Mi"
              cpu: "300m"
            limits:
              memory: "128Mi"
              cpu: "2000m"
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: backend-config
          env:
            - name: ALLOW_ORIGIN
              valueFrom:
                secretKeyRef:
                  key: ALLOW_ORIGIN
                  name: env-secret
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: ACCESS_TOKEN_SECRET
                  name: env-secret
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  key: CHAT_ID
                  name: env-secret