apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: tg-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: ghcr.io/nrf24l01/tg_group_statistics/parser:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
              name: db-config
            - configMapRef:
              name: backend-config