apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleton-session
  namespace: tg-stats
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Mi
  storageClassName: ""